"use client";

import { useEffect, useState } from "react";
import { Activity, CheckCircle2, AlertOctagon, Clock } from "lucide-react";
import { cn } from "@/lib/utils";

interface PassSummaryCardProps {
  summary: any;
  loading: boolean;
}

export default function PassSummaryCard({ summary, loading }: PassSummaryCardProps) {
  const [expanded, setExpanded] = useState(false);

  if (loading) {
    return (
      <div className="flex h-64 w-full flex-col items-center justify-center space-y-3 rounded-xl border border-border bg-card/50">
        <Activity className="h-6 w-6 animate-pulse text-muted-foreground" />
        <span className="text-sm text-muted-foreground">Generating summary via GPT-4o...</span>
      </div>
    );
  }

  if (!summary || summary.status === "NO_DATA") {
    return (
      <div className="flex p-6 w-full items-center justify-center rounded-xl border border-border bg-card/50 text-muted-foreground">
        No telemetry data to summarize for this pass.
      </div>
    );
  }

  const isNominal = summary.status === "NOMINAL";

  return (
    <div className={cn(
      "overflow-hidden rounded-xl border bg-card transition-colors",
      isNominal ? "border-green-500/20" : "border-destructive/50"
    )}>
      <div className={cn(
        "flex items-center justify-between border-b p-4",
        isNominal ? "border-green-500/20 bg-green-500/5" : "border-destructive/20 bg-destructive/5"
      )}>
        <div className="flex items-center space-x-2">
          {isNominal ? (
            <CheckCircle2 className="h-5 w-5 text-green-500" />
          ) : (
            <AlertOctagon className="h-5 w-5 text-destructive" />
          )}
          <h3 className={cn(
            "font-bold tracking-tight",
            isNominal ? "text-green-500" : "text-destructive"
          )}>
            PASS {summary.status}
          </h3>
        </div>
        
        {summary.pass_duration && (
          <div className="flex items-center text-xs text-muted-foreground">
            <Clock className="mr-1 h-3 w-3" />
            {Math.floor(summary.pass_duration / 60)}m {summary.pass_duration % 60}s
          </div>
        )}
      </div>
      
      <div className="p-5">
        <div className="prose prose-sm prose-invert max-w-none mb-6 text-foreground/90 leading-relaxed whitespace-pre-wrap">
          {summary.summary_text}
        </div>
        
        <div className="flex justify-between items-center border-t border-border pt-4">
          <span className="text-xs text-muted-foreground">Generated by Orbitwatch AI</span>
          <button 
            onClick={() => setExpanded(!expanded)}
            className="text-xs font-medium text-primary hover:underline hover:underline-offset-4"
          >
            {expanded ? "Hide Data Table" : "View Parameter Detail"}
          </button>
        </div>
      </div>
      
      {expanded && summary.parameters && (
        <div className="border-t border-border bg-background p-0">
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead className="bg-muted text-muted-foreground">
                <tr>
                  <th className="px-4 py-2 font-medium">Parameter</th>
                  <th className="px-4 py-2 font-medium text-right">Mean</th>
                  <th className="px-4 py-2 font-medium text-right">Historical</th>
                  <th className="px-4 py-2 font-medium">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                {Object.entries(summary.parameters).map(([key, data]: [string, any]) => (
                  <tr key={key} className={data.anomaly_flag ? "bg-destructive/10" : ""}>
                    <td className="px-4 py-2 font-medium">{key}</td>
                    <td className="px-4 py-2 text-right">{data.mean?.toFixed(2) || "N/A"}</td>
                    <td className="px-4 py-2 text-right">{data.historical_mean?.toFixed(2) || "N/A"}</td>
                    <td className={cn(
                      "px-4 py-2",
                      data.anomaly_flag ? "text-destructive font-medium" : "text-muted-foreground"
                    )}>
                      {data.vs_historical}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>
      )}
    </div>
  );
}
